const hintCommands = [
    {commandName: "/aatc [message]", staff: false},
    {commandName: "/abcashbox [type] [amount]", staff: false},
    {commandName: "/abortcharger", staff: false},
    {commandName: "/abortsale", staff: false},
    {commandName: "/acceptbreakup [playerid]", staff: false},
    {commandName: "/acceptcarry", staff: false},
    {commandName: "/acceptdeath", staff: false},
    {commandName: "/acceptfriend [Friend ID] [Nickname(optional)]", staff: false},
    {commandName: "/acceptgag", staff: false},
    {commandName: "/acceptgreet", staff: false},
    {commandName: "/acceptheal", staff: false},
    {commandName: "/accepthoist", staff: false},
    {commandName: "/acceptkey", staff: false},
    {commandName: "/acceptorder [orderId]", staff: false},
    {commandName: "/acceptpartner [playerid]", staff: false},
    {commandName: "/acceptrecruit", staff: false},
    {commandName: "/acceptrobbery", staff: false},
    {commandName: "/acceptsafekey", staff: false},
    {commandName: "/acceptsale [propertyId]", staff: false},
    {commandName: "/acceptseat", staff: false},
    {commandName: "/accessories [on/off]", staff: false},
    {commandName: "/adbizjob [description]", staff: false},
    {commandName: "/addattachment", staff: false},
    {commandName: "/addcat [target]", staff: false},
    {commandName: "/addcontact [number] [name]", staff: false},
    {commandName: "/addfriend [Friend ID] [Nickname(optional)]", staff: false},
    {commandName: "/adjob [description]", staff: false},
    {commandName: "/admins", staff: false},
    {commandName: "/adorgjob [description]", staff: false},
    {commandName: "/ads", staff: false},
    {commandName: "/advert [text]", staff: false},
    {commandName: "/alpr", staff: false},
    {commandName: "/alprsize [70-100]", staff: false},
    {commandName: "/ame [message]", staff: false},
    {commandName: "/amy [message]", staff: false},
    {commandName: "/anchor", staff: false},
    {commandName: "/anim [help/animation_name/search/favorite/unfavorite/stop] (animation_name)", staff: false},
    {commandName: "/anklemonitor [targ]", staff: false},
    {commandName: "/ann [message]", staff: false},
    {commandName: "/applycustomnumber [confirm]", staff: false},
    {commandName: "/approvehospital [Request ID] - /hospitalrequests to see all active requests.", staff: false},
    {commandName: "/approvemorgue [Request ID] - /morguerequests to see all active requests.", staff: false},
    {commandName: "/arrest [PlayerID/PartOfName] [Days] [Hours] [Minutes]", staff: false},
    {
        commandName: "/arrestcounty [target] [days] [hours] [minutes] [Male/Female/D-Seg/Protecting/CellID] [Wristband (Blue/Yellow/Red)] [Bracelet (White/Orange)]",
        staff: false
    },
    {commandName: "/as", staff: false},
    {commandName: "/assigncell [targ]", staff: false},
    {commandName: "/assignicon [item index (/myinvex)] [confirm]", staff: false},
    {commandName: "/atc [message]", staff: false},
    {commandName: "/atporder [targ]", staff: false},
    {commandName: "/att", staff: false},
    {commandName: "/autogrammar", staff: false},
    {commandName: "/autolow", staff: false},
    {commandName: "/autop", staff: false},
    {commandName: "/b [Local OOC Chat]", staff: false},
    {commandName: "/badblip", staff: false},
    {commandName: "/badge [targ]", staff: false},
    {commandName: "/badname [name]", staff: false},
    {commandName: "/badtext [text]", staff: false},
    {commandName: "/bankdata", staff: false},
    {commandName: "/bar [commandText]", staff: false},
    {commandName: "/bcashbox [type] [amount]", staff: false},
    {commandName: "/bdeliverypoint [businessID] [confirm]", staff: false},
    {commandName: "/bdemote [targ]", staff: false},
    {commandName: "/bdeposit [Amount] [Comment (optional)]", staff: false},
    {commandName: "/bell", staff: false},
    {commandName: "/bfire [targ]", staff: false},
    {commandName: "/bikehelmet", staff: false},
    {commandName: "/bjoin [confirm]", staff: false},
    {commandName: "/blanks [type]", staff: false},
    {commandName: "/bleave [confirm]", staff: false},
    {commandName: "/blindfold", staff: false},
    {commandName: "/blockpm [targ]", staff: false},
    {commandName: "/bloodstats", staff: false},
    {commandName: "/blow [Local OOC Chat] - Low chat radius.", staff: false},
    {commandName: "/bmethod [exclusive paymethod] (e.g Cash, Bank, All)", staff: false},
    {commandName: "/bodyarmour [on/off]", staff: false},
    {commandName: "/boomboxvolume [Volume (1 - 100)]", staff: false},
    {commandName: "/bpaccept [hash]", staff: false},
    {commandName: "/bpay [target] [amount]", staff: false},
    {commandName: "/bpercentshare [amount]", staff: false},
    {commandName: "/bpromote [targ]", staff: false},
    {commandName: "/bra [on/off]", staff: false},
    {commandName: "/bracelet [on/off]", staff: false},
    {commandName: "/breakin [requestText]", staff: false},
    {commandName: "/breakup [playerid]", staff: false},
    {commandName: "/breakupinactivity [playerid]", staff: false},
    {commandName: "/brecruit [targ]", staff: false},
    {commandName: "/brew", staff: false},
    {commandName: "/brewer [confirm]", staff: false},
    {commandName: "/btransfer [Amount] [Routing or Player ID] [Comment (optional)]", staff: false},
    {commandName: "/bugphone [number]", staff: false},
    {commandName: "/businessadvert", staff: false},
    {commandName: "/businessblip", staff: false},
    {commandName: "/businessmanager", staff: false},
    {commandName: "/businessmenu", staff: false},
    {commandName: "/buybusiness [confirm]", staff: false},
    {commandName: "/buycomp", staff: false},
    {commandName: "/buyplayervehicle [vehicle id] [Bank/Cash]", staff: false},
    {commandName: "/buyproperty [confirm]", staff: false},
    {commandName: "/buyvehicle", staff: false},
    {commandName: "/bwithdraw [Amount] [Comment (optional)]", staff: false},
    {commandName: "/calculator [first number] [* / + -] [second number]", staff: false},
    {commandName: "/call [number or name]", staff: false},
    {commandName: "/callhistory [limit (max 20)]", staff: false},
    {commandName: "/camera", staff: false},
    {commandName: "/cancelbreakin", staff: false},
    {commandName: "/cancelcontract [id] [confirm]", staff: false},
    {commandName: "/cancelfirerequest", staff: false},
    {commandName: "/cancelhelpme", staff: false},
    {commandName: "/cancelorder", staff: false},
    {commandName: "/cancelpreview", staff: false},
    {commandName: "/cancelrental", staff: false},
    {commandName: "/cancelreport", staff: false},
    {commandName: "/cancelroute [print]", staff: false},
    {commandName: "/canceltaxi", staff: false},
    {commandName: "/canceltutorial", staff: false},
    {commandName: "/canine", staff: false},
    {commandName: "/carsign [signText]", staff: false},
    {commandName: "/carwash", staff: false},
    {commandName: "/casing [commandText]", staff: false},
    {commandName: "/castnet", staff: false},
    {commandName: "/cat", staff: false},
    {commandName: "/catch", staff: false},
    {commandName: "/cb [message]", staff: false},
    {commandName: "/cbury", staff: false},
    {commandName: "/cctv", staff: false},
    {commandName: "/cdrag", staff: false},
    {commandName: "/cellinfo [id]", staff: false},
    {commandName: "/celltp", staff: false},
    {commandName: "/cexamine", staff: false},
    {commandName: "/changechar", staff: false},
    {commandName: "/changelog", staff: false},
    {commandName: "/changeuniform [slot]", staff: false},
    {commandName: "/characterdetails", staff: false},
    {commandName: "/characternotes", staff: false},
    {commandName: "/charity [Option (hand/bank)] [Amount]", staff: false},
    {commandName: "/chatsize [size]", staff: false},
    {commandName: "/checkalcohol [targ]", staff: false},
    {commandName: "/checkallsamples [Evidence Label]", staff: false},
    {commandName: "/checkblood", staff: false},
    {commandName: "/checkcell [targ]", staff: false},
    {commandName: "/checkdirt", staff: false},
    {commandName: "/checkdrugeffects [targ]", staff: false},
    {commandName: "/checkfines [targ]", staff: false},
    {commandName: "/checkinformation [firstnameLastname]", staff: false},
    {commandName: "/checkjduty [Firstname] [Lastname] [Month (Number)] [Year (Number)]", staff: false},
    {commandName: "/checklang", staff: false},
    {commandName: "/checkplate [plate]", staff: false},
    {commandName: "/checksample [Item ID (see /inv to get the blood sample ID)] [Evidence Label]", staff: false},
    {commandName: "/checkseatbelt [targ]", staff: false},
    {commandName: "/checkserial [serial]", staff: false},
    {commandName: "/checktime [targ]", staff: false},
    {commandName: "/checktint", staff: false},
    {
        commandName: "/checkvehiclefines [leave empty for closest car, fill ID or part of name to check a players vehicle fines]",
        staff: false
    },
    {commandName: "/cinfo", staff: false},
    {commandName: "/cleanads", staff: false},
    {commandName: "/cleanblood", staff: false},
    {commandName: "/cleanset", staff: false},
    {commandName: "/clearcall", staff: false},
    {commandName: "/clearchat", staff: false},
    {commandName: "/cleartask", staff: false},
    {commandName: "/cleartattoos", staff: false},
    {commandName: "/closebusiness", staff: false},
    {commandName: "/cmorgue", staff: false},
    {commandName: "/companyadvert [text]", staff: false},
    {commandName: "/companyadvertlocation [text]", staff: false},
    {commandName: "/condom", staff: false},
    {commandName: "/construction", staff: false},
    {commandName: "/contacts [sorting type 1-5]", staff: false},
    {commandName: "/containerbreakin [storage id]", staff: false},
    {commandName: "/containerdescription [storage id (if needed)]", staff: false},
    {commandName: "/containeritems [storage id(if needed)]", staff: false},
    {commandName: "/containerlock [storage id]", staff: false},
    {commandName: "/containername [storage id] [name]", staff: false},
    {commandName: "/coords", staff: false},
    {commandName: "/coronerduty [Callsign]", staff: false},
    {commandName: "/coroneroutfit [on/off]", staff: false},
    {commandName: "/corpsedamages", staff: false},
    {commandName: "/corpsedna", staff: false},
    {commandName: "/courier", staff: false},
    {commandName: "/cpitem [itemid] [amount] [storage item (if required)]", staff: false},
    {commandName: "/createdrink [base_alcohol_id] [amount] [name]", staff: false},
    {commandName: "/createinformationmarker [days] [description] [image url: optional]", staff: false},
    {commandName: "/createitem [type] [value] [amount] [name]", staff: false},
    {commandName: "/createlastdrink [amount] [confirm]", staff: false},
    {commandName: "/createlastitem [amount] [confirm]", staff: false},
    {commandName: "/createscene [duration] [description]", staff: false},
    {commandName: "/cremove", staff: false},
    {commandName: "/ctitem [itemid] [amount] [storage item (if required)]", staff: false},
    {commandName: "/ctp [id]", staff: false},
    {commandName: "/ctrunk", staff: false},
    {commandName: "/cuff [targ]", staff: false},
    {commandName: "/cw [message]", staff: false},
    {commandName: "/damage [target]", staff: false},
    {commandName: "/damageme [damage]", staff: false},
    {commandName: "/damages [target]", staff: false},
    {commandName: "/decals [on/off]", staff: false},
    {commandName: "/delblip", staff: false},
    {commandName: "/deleteallcasings [confirm]", staff: false},
    {commandName: "/deletecasings [range]", staff: false},
    {commandName: "/deleteinformationmarker", staff: false},
    {commandName: "/deletelastobject", staff: false},
    {commandName: "/deletemyinformationmarkers", staff: false},
    {commandName: "/deletemyscenes", staff: false},
    {commandName: "/deletescene", staff: false},
    {commandName: "/deletevehicle [id]", staff: false},
    {commandName: "/delivercrate", staff: false},
    {commandName: "/denyhospital [Request ID] - /hospitalrequests to see all active requests.", staff: false},
    {commandName: "/denymorgue [Request ID] - /morguerequests to see all active requests.", staff: false},
    {commandName: "/denyorder [orderId]", staff: false},
    {commandName: "/department [message] - Use /setdep to set the targeted faction.", staff: false},
    {commandName: "/departmentlow [message] - Use /setdep to set the targeted faction.", staff: false},
    {commandName: "/depfactions", staff: false},
    {commandName: "/deposit [To Routing? Leave Empty for Personal Account]", staff: false},
    {commandName: "/description [message]", staff: false},
    {commandName: "/detach [weapon id] [attachment id]", staff: false},
    {commandName: "/detachcharger", staff: false},
    {commandName: "/devicedestroy [confirm]", staff: false},
    {commandName: "/devicedisable [device_id]", staff: false},
    {commandName: "/devicefaction [device_id]", staff: false},
    {commandName: "/devicejoin [id]", staff: false},
    {commandName: "/devicelist", staff: false},
    {commandName: "/devicemute [id]", staff: false},
    {commandName: "/devicename [device_id] [name]", staff: false},
    {commandName: "/devicepick [confirm]", staff: false},
    {commandName: "/devicetrack [id]", staff: false},
    {commandName: "/devtptodoor [id]", staff: false},
    {commandName: "/dice", staff: false},
    {commandName: "/dimension", staff: false},
    {commandName: "/do [emote]", staff: false},
    {commandName: "/dog", staff: false},
    {commandName: "/dolong [emote]", staff: false},
    {commandName: "/dolow [emote]", staff: false},
    {commandName: "/domelight", staff: false},
    {commandName: "/doordo [text]", staff: false},
    {commandName: "/doorme [text]", staff: false},
    {commandName: "/doorshout [text]", staff: false},
    {commandName: "/drag [targ]", staff: false},
    {commandName: "/dropcrate", staff: false},
    {commandName: "/dropitem [itemid] [amount]", staff: false},
    {commandName: "/dropweapon [index] [confirm]", staff: false},
    {commandName: "/drugcut [index] [amount]", staff: false},
    {commandName: "/druginfo", staff: false},
    {commandName: "/drugname [index] [amount] [name]", staff: false},
    {commandName: "/drugtest [index]", staff: false},
    {commandName: "/dsadd [price]", staff: false},
    {commandName: "/dsremove", staff: false},
    {commandName: "/duplicatekey [targ] [VID]", staff: false},
    {commandName: "/dutyroster", staff: false},
    {commandName: "/ears [on/off]", staff: false},
    {commandName: "/election [cmdText]", staff: false},
    {commandName: "/enablepointing", staff: false},
    {commandName: "/endcontract", staff: false},
    {commandName: "/endshift", staff: false},
    {commandName: "/engine", staff: false},
    {commandName: "/enter", staff: false},
    {commandName: "/equip [itemid]", staff: false},
    {commandName: "/equipment [unit] [index] [type]", staff: false},
    {commandName: "/evictall", staff: false},
    {commandName: "/evidencelocker", staff: false},
    {commandName: "/examine [targ]", staff: false},
    {commandName: "/examinecasings", staff: false},
    {commandName: "/exit", staff: false},
    {commandName: "/exitcar", staff: false},
    {commandName: "/exteriorkit", staff: false},
    {commandName: "/faccept", staff: false},
    {commandName: "/face [expression]", staff: false},
    {commandName: "/faction", staff: false},
    {commandName: "/factionduty", staff: false},
    {commandName: "/factioninvite [targ]", staff: false},
    {commandName: "/factiononline", staff: false},
    {commandName: "/factionowner [targ]", staff: false},
    {commandName: "/factionrank [targ] [rank]", staff: false},
    {commandName: "/factionrankname [target] [custom name/Clear]", staff: false},
    {commandName: "/factionremove [targ]", staff: false},
    {commandName: "/fare [price]", staff: false},
    {commandName: "/fbank", staff: false},
    {commandName: "/fcad", staff: false},
    {commandName: "/fchat [message]", staff: false},
    {commandName: "/fcolor [colour]", staff: false},
    {commandName: "/fdeposit [money] [comment]", staff: false},
    {commandName: "/feedplant", staff: false},
    {commandName: "/findcharger", staff: false},
    {commandName: "/findtrash", staff: false},
    {commandName: "/fine [targ] [amount] [reason]", staff: false},
    {commandName: "/fines", staff: false},
    {commandName: "/fingernails", staff: false},
    {commandName: "/firemanager", staff: false},
    {commandName: "/fishing", staff: false},
    {commandName: "/fixdoors", staff: false},
    {commandName: "/fixfall", staff: false},
    {commandName: "/fixinvi [freeze]", staff: false},
    {commandName: "/fixlicenses", staff: false},
    {commandName: "/fixlights", staff: false},
    {commandName: "/fixloc", staff: false},
    {commandName: "/fixoutfit [confirm]", staff: false},
    {commandName: "/fixoutfits [confirm]", staff: false},
    {commandName: "/fixr", staff: false},
    {commandName: "/fixrevive", staff: false},
    {commandName: "/fixtextures", staff: false},
    {commandName: "/fixveh", staff: false},
    {commandName: "/flipcoin", staff: false},
    {commandName: "/font", staff: false},
    {commandName: "/forward [range]", staff: false},
    {commandName: "/frankwage [rank] [amount]", staff: false},
    {commandName: "/friendalert [Friend ID]", staff: false},
    {commandName: "/friendname [Friend ID] [Nickname (use 'clear' to remove nickname)]", staff: false},
    {commandName: "/friends", staff: false},
    {commandName: "/frisk [targ]", staff: false},
    {commandName: "/fspawn", staff: false},
    {commandName: "/ftow", staff: false},
    {commandName: "/ftransfer [Amount] [Routing or Player ID] [Comment (optional)]", staff: false},
    {commandName: "/fuel [percentage to fill to 10-100]", staff: false},
    {commandName: "/furniture", staff: false},
    {commandName: "/furnrotation [x] [y] [z] (the script rounds up to two decimals e.g. 22.50)", staff: false},
    {commandName: "/fwageoff", staff: false},
    {commandName: "/fwageon", staff: false},
    {commandName: "/fwageperm", staff: false},
    {commandName: "/fwithdraw [money] [comment]", staff: false},
    {commandName: "/garage", staff: false},
    {commandName: "/garbage", staff: false},
    {commandName: "/garbagereset", staff: false},
    {commandName: "/gate [gateid]", staff: false},
    {commandName: "/gdeleteinformationmarker [confirm]", staff: false},
    {commandName: "/gduty", staff: false},
    {commandName: "/getdnastring [firstname] [lastname]", staff: false},
    {commandName: "/getfuelconsumption", staff: false},
    {commandName: "/getup", staff: false},
    {commandName: "/giveboombox [target]", staff: false},
    {commandName: "/givejailuniform", staff: false},
    {commandName: "/givechargerpermission [target]", staff: false},
    {commandName: "/givedriverlicense [targ]", staff: false},
    {commandName: "/giveitem [targ] [itemid] [amount]", staff: false},
    {
        commandName: "/givelicense [target] [licenseid] [price] (1=Driving license, 2=PF, 3=CCW, 4=LEOCCW, 5=Copper, 6=Iron, 7=Aluminium, 8=Guardcard, 9=Hunting, 12=Pilot, 18=CFIA, 19=CFIH, 20=PilotA, 21=PilotH)",
        staff: false
    },
    {commandName: "/givelockbox [storage id] [player]", staff: false},
    {commandName: "/givepropertykey [targ]", staff: false},
    {commandName: "/givesafekey [targ]", staff: false},
    {commandName: "/glasses [on/off]", staff: false},
    {commandName: "/gloves [none/help]", staff: false},
    {commandName: "/govannouncement [text]", staff: false},
    {commandName: "/gown [on/off]", staff: false},
    {commandName: "/gps [address]", staff: false},
    {commandName: "/graffiti", staff: false},
    {commandName: "/greet [targ]", staff: false},
    {
        commandName: "/hairtie [none, bun(2-5), highbun(2-5), ponytail, longponytail(2-5), pigtail(2), braids(2-3), sidebraid, fancy(2), hat(2)]",
        staff: false
    },
    {commandName: "/hands [on/off]", staff: false},
    {commandName: "/hangup", staff: false},
    {commandName: "/harvest", staff: false},
    {commandName: "/hat [on/off]", staff: false},
    {commandName: "/headlights", staff: false},
    {commandName: "/heal [targ]", staff: false},
    {commandName: "/helif", staff: false},
    {commandName: "/helmet", staff: false},
    {commandName: "/help", staff: false},
    {commandName: "/helpme [question]", staff: false},
    {commandName: "/helpup [targ]", staff: false},
    {commandName: "/hidenames", staff: false},
    {commandName: "/hideweapon [weapon]", staff: false},
    {commandName: "/highlight [target] ['clear' to turn off highlighting]", staff: false},
    {commandName: "/highlightcolour [hex digits (e.g. FF00C3)]", staff: false},
    {commandName: "/hoist [playerid]", staff: false},
    {commandName: "/hoistto [playerid]", staff: false},
    {commandName: "/hood", staff: false},
    {commandName: "/hose", staff: false},
    {commandName: "/hospitalduty", staff: false},
    {commandName: "/hospitalrequests", staff: false},
    {commandName: "/hotwire", staff: false},
    {commandName: "/hq [ic_or_ooc] [message]", staff: false},
    {commandName: "/hud", staff: false},
    {commandName: "/hudoffset [X offset] [Y offset]", staff: false},
    {commandName: "/iconpicker", staff: false},
    {commandName: "/impound [days]", staff: false},
    {commandName: "/injuries [player ID or name]", staff: false},
    {commandName: "/inmates", staff: false},
    {commandName: "/input [input]", staff: false},
    {commandName: "/inspect [restore] [weapon]", staff: false},
    {commandName: "/installalarm [alarmName]", staff: false},
    {commandName: "/installcharger", staff: false},
    {commandName: "/intercom [msg]", staff: false},
    {commandName: "/interinvite [targ]", staff: false},
    {commandName: "/interview [text]", staff: false},
    {commandName: "/immersive", staff: false},
    {commandName: "/jailcharacter [confirm]", staff: false},
    {commandName: "/jailcustomize", staff: false},
    {commandName: "/jailduty", staff: false},
    {commandName: "/jailevent [event_text]", staff: false},
    {commandName: "/jailrequest [description]", staff: false},
    {commandName: "/jailtime", staff: false},
    {commandName: "/jailtoggleuniform", staff: false},
    {commandName: "/jailuniform", staff: false},
    {commandName: "/jetskipassenger", staff: false},
    {commandName: "/jlockdown [status]", staff: false},
    {commandName: "/joinnews", staff: false},
    {commandName: "/jointable [money]", staff: false},
    {commandName: "/kicksafekey [keyid]", staff: false},
    {commandName: "/kicktable [player]", staff: false},
    {commandName: "/kicktenant [tenantId]", staff: false},
    {commandName: "/knock", staff: false},
    {commandName: "/lang [lang]", staff: false},
    {commandName: "/lawyer [targ]", staff: false},
    {commandName: "/leavefaction [confirm]", staff: false},
    {commandName: "/leavejob", staff: false},
    {commandName: "/leavetable", staff: false},
    {commandName: "/licenses", staff: false},
    {commandName: "/listopenbusiness", staff: false},
    {commandName: "/loadcrate", staff: false},
    {commandName: "/loadgoods", staff: false},
    {commandName: "/loadmapipl [load]", staff: false},
    {commandName: "/loadtuners", staff: false},
    {commandName: "/lockvehicle [overrideVehicle]", staff: false},
    {commandName: "/login [userName] [password]", staff: false},
    {commandName: "/loudspeaker", staff: false},
    {commandName: "/low [message]", staff: false},
    {commandName: "/lowto [targ] [message]", staff: false},
    {commandName: "/m [message]", staff: false},
    {commandName: "/mail", staff: false},
    {commandName: "/makedrugs [drug]", staff: false},
    {commandName: "/makelobby [player slots (max 10)] [Table (yes/no)]", staff: false},
    {commandName: "/maketable [player slots (max 5)] [minimum bet] [maximum bet]", staff: false},
    {commandName: "/makeup", staff: false},
    {commandName: "/mask", staff: false},
    {commandName: "/maskname", staff: false},
    {commandName: "/mcallsign [callsign]", staff: false},
    {commandName: "/mdc", staff: false},
    {commandName: "/mdcmenu", staff: false},
    {commandName: "/me [message]", staff: false},
    {commandName: "/mechanic [confirm]", staff: false},
    {commandName: "/medicduty [Callsign]", staff: false},
    {commandName: "/melong [message]", staff: false},
    {commandName: "/melow [message]", staff: false},
    {commandName: "/menu [action] [parameter?]", staff: false},
    {commandName: "/mequipment [unit]", staff: false},
    {commandName: "/messages [limit (max 20)]", staff: false},
    {commandName: "/metallurgist [confirm]", staff: false},
    {commandName: "/mic [message]", staff: false},
    {commandName: "/mincident [title/location/situation/done] [text]", staff: false},
    {commandName: "/morguerequests", staff: false},
    {commandName: "/motorhelmet", staff: false},
    {commandName: "/movemenu [offsetX] [offsetY]", staff: false},
    {commandName: "/mplace [slotId]", staff: false},
    {commandName: "/mstatus [id]", staff: false},
    {commandName: "/mtake [slotId]", staff: false},
    {commandName: "/mute [targ]", staff: false},
    {commandName: "/muteradio [slot]", staff: false},
    {commandName: "/my [message]", staff: false},
    {commandName: "/mycell", staff: false},
    {commandName: "/mycontracts", staff: false},
    {commandName: "/mydep", staff: false},
    {commandName: "/myfish", staff: false},
    {commandName: "/myitems", staff: false},
    {commandName: "/myitemsex", staff: false},
    {commandName: "/mylong [message]", staff: false},
    {commandName: "/mylow [message]", staff: false},
    {commandName: "/myphones", staff: false},
    {commandName: "/myproperty", staff: false},
    {commandName: "/myvehicles", staff: false},
    {commandName: "/namephone [new phone name ('none' to clear)]", staff: false},
    {commandName: "/news [text]", staff: false},
    {commandName: "/newsrating", staff: false},
    {commandName: "/niners", staff: false},
    {commandName: "/nof", staff: false},
    {commandName: "/notafk", staff: false},
    {commandName: "/note [Inventory ID] [Amount] [Name/Content/Icon/Help] [Text]", staff: false},
    {commandName: "/notifications", staff: false},
    {commandName: "/oldradar [distance] [size] [speed limit]", staff: false},
    {commandName: "/oldradaroff", staff: false},
    {commandName: "/onduty", staff: false},
    {commandName: "/ooc [message]", staff: false},
    {commandName: "/openbusiness", staff: false},
    {commandName: "/orderdevices", staff: false},
    {commandName: "/orders", staff: false},
    {commandName: "/outfit [slot]", staff: false},
    {commandName: "/outfitname [slot] [name (use 'clear' to clear the name)]", staff: false},
    {commandName: "/panic", staff: false},
    {commandName: "/panties [on/off]", staff: false},
    {commandName: "/pants [on/off]", staff: false},
    {commandName: "/parolemonitor [Trace/List] [TargetID/PartOfName]", staff: false},
    {commandName: "/part", staff: false},
    {commandName: "/partall", staff: false},
    {commandName: "/partner [playerid]", staff: false},
    {commandName: "/partnerinfo", staff: false},
    {commandName: "/passcig [Player ID/Part Of Name]", staff: false},
    {commandName: "/passjoint [Player ID/Part Of Name]", staff: false},
    {commandName: "/pautolow", staff: false},
    {commandName: "/pay [targ] [money]", staff: false},
    {commandName: "/paydebt [amount]", staff: false},
    {commandName: "/payfine [id]", staff: false},
    {commandName: "/payphonecall [number]", staff: false},
    {commandName: "/paytaxi [targ] [money]", staff: false},
    {commandName: "/pbonus", staff: false},
    {commandName: "/pbreakin", staff: false},
    {commandName: "/pcallsign [callsign]", staff: false},
    {commandName: "/pdstop", staff: false},
    {commandName: "/pedoff [type]", staff: false},
    {commandName: "/pedon [type]", staff: false},
    {commandName: "/pentrance", staff: false},
    {commandName: "/petdespawn", staff: false},
    {commandName: "/petdo [message]", staff: false},
    {commandName: "/petexamine [targ]", staff: false},
    {commandName: "/petmanager", staff: false},
    {commandName: "/petme [message]", staff: false},
    {commandName: "/pexitangle", staff: false},
    {commandName: "/pextdim [extDim]", staff: false},
    {commandName: "/pfreeze", staff: false},
    {commandName: "/phone [nameornumber]", staff: false},
    {commandName: "/phonecursor", staff: false},
    {commandName: "/phonedirectory", staff: false},
    {commandName: "/phonehelp", staff: false},
    {commandName: "/phoneon", staff: false},
    {commandName: "/phonesize [70-100]", staff: false},
    {commandName: "/pickup", staff: false},
    {commandName: "/pickupcontainer [confirm]", staff: false},
    {commandName: "/pickupcrate", staff: false},
    {commandName: "/pinteriorprops", staff: false},
    {commandName: "/place [slotId]", staff: false},
    {commandName: "/placecontainer [storage id] [confirm]", staff: false},
    {commandName: "/placeorder", staff: false},
    {commandName: "/placesafe [version]", staff: false},
    {commandName: "/placespike", staff: false},
    {commandName: "/placewire [targ]", staff: false},
    {commandName: "/plant", staff: false},
    {commandName: "/playercount", staff: false},
    {commandName: "/playerid [target]", staff: false},
    {commandName: "/playersellhouse [price] [targ] [confirm]", staff: false},
    {commandName: "/plocation [location]", staff: false},
    {commandName: "/pm [targ] [message]", staff: false},
    {commandName: "/pma [targ] [message]", staff: false},
    {commandName: "/pmall [message]", staff: false},
    {commandName: "/policeduty [callsign]", staff: false},
    {commandName: "/policehat", staff: false},
    {commandName: "/policehat2", staff: false},
    {commandName: "/policehelp", staff: false},
    {commandName: "/poolpickup", staff: false},
    {commandName: "/poolplay", staff: false},
    {commandName: "/pooltable", staff: false},
    {commandName: "/ppitem [itemid] [amount]", staff: false},
    {commandName: "/ppitems", staff: false},
    {commandName: "/pray", staff: false},
    {commandName: "/preload", staff: false},
    {commandName: "/prisontake [Help/SlotID]", staff: false},
    {commandName: "/propdespawn [property_id]", staff: false},
    {commandName: "/propertybusiness [businessId]", staff: false},
    {commandName: "/propertydeposit [amount]", staff: false},
    {commandName: "/propertyfaction", staff: false},
    {commandName: "/propertyfee [fee]", staff: false},
    {commandName: "/propertyitems", staff: false},
    {commandName: "/propertylock", staff: false},
    {commandName: "/propertymanager [propertyID]", staff: false},
    {commandName: "/propertyunbusiness", staff: false},
    {commandName: "/propertywithdraw [amount]", staff: false},
    {commandName: "/propertywithdrawall", staff: false},
    {commandName: "/propobjects", staff: false},
    {commandName: "/pshare [targ]", staff: false},
    {commandName: "/pstatus [status]", staff: false},
    {commandName: "/pt [text]", staff: false},
    {commandName: "/ptime [time]", staff: false},
    {commandName: "/ptitem [itemid] [amount]", staff: false},
    {commandName: "/ptitems", staff: false},
    {commandName: "/pullincar [targ]", staff: false},
    {commandName: "/pulloutcar [targ]", staff: false},
    {commandName: "/putboombox", staff: false},
    {commandName: "/puthandle", staff: false},
    {commandName: "/putjaillock [autolock yes/no]", staff: false},
    {commandName: "/putlock", staff: false},
    {commandName: "/pvlock [overrideVehicle]", staff: false},
    {commandName: "/pweather [weather]", staff: false},
    {commandName: "/quitgarbage", staff: false},
    {commandName: "/radar [type] [value]", staff: false},
    {commandName: "/radio [message]", staff: false},
    {commandName: "/radio1 [message]", staff: false},
    {commandName: "/radio2 [message]", staff: false},
    {commandName: "/radio3 [message]", staff: false},
    {commandName: "/radio4 [message]", staff: false},
    {commandName: "/radio5 [message]", staff: false},
    {commandName: "/radio6 [message]", staff: false},
    {commandName: "/radio7 [message]", staff: false},
    {commandName: "/radio8 [message]", staff: false},
    {commandName: "/radio9 [message]", staff: false},
    {commandName: "/radiohelp", staff: false},
    {commandName: "/radiohide", staff: false},
    {commandName: "/radiolow [message]", staff: false},
    {commandName: "/radiolow1 [message]", staff: false},
    {commandName: "/radiolow2 [message]", staff: false},
    {commandName: "/radiolow3 [message]", staff: false},
    {commandName: "/radiolow4 [message]", staff: false},
    {commandName: "/radiolow5 [message]", staff: false},
    {commandName: "/radiolow6 [message]", staff: false},
    {commandName: "/radiolow7 [message]", staff: false},
    {commandName: "/radiolow8 [message]", staff: false},
    {commandName: "/radiolow9 [message]", staff: false},
    {commandName: "/radioshow", staff: false},
    {commandName: "/ragdoll", staff: false},
    {commandName: "/ramp", staff: false},
    {commandName: "/rappel", staff: false},
    {commandName: "/re [message]", staff: false},
    {commandName: "/recharge", staff: false},
    {commandName: "/refresh", staff: false},
    {commandName: "/registerpf [itemid]", staff: false},
    {commandName: "/release [targ]", staff: false},
    {commandName: "/releaseme", staff: false},
    {commandName: "/reloadallprops", staff: false},
    {commandName: "/reloadEMD", staff: false},
    {commandName: "/reloadprop", staff: false},
    {commandName: "/removealarm", staff: false},
    {commandName: "/removeallnotifications", staff: false},
    {commandName: "/removeanklemonitor [targ]", staff: false},
    {commandName: "/removecontact [phone number or contact name]", staff: false},
    {commandName: "/removecrate", staff: false},
    {commandName: "/removefine [targ] [id]", staff: false},
    {commandName: "/removefriend [Friend ID]", staff: false},
    {commandName: "/removegag [PlayerID/PartOfName]", staff: false},
    {commandName: "/removehandle", staff: false},
    {commandName: "/removejaillock", staff: false},
    {commandName: "/removelocation", staff: false},
    {commandName: "/removelock", staff: false},
    {commandName: "/removemyanklemonitor", staff: false},
    {commandName: "/removenotification [notid]", staff: false},
    {commandName: "/removeserial [index]", staff: false},
    {commandName: "/removespike", staff: false},
    {commandName: "/removetable", staff: false},
    {commandName: "/removetrace", staff: false},
    {commandName: "/rent [confirm]", staff: false},
    {commandName: "/renttaxi", staff: false},
    {commandName: "/rentvehicle", staff: false},
    {commandName: "/repair", staff: false},
    {commandName: "/report [problem]", staff: false},
    {commandName: "/reportvehiclefound [licensePlate]", staff: false},
    {commandName: "/reportvehiclestolen [licensePlate]", staff: false},
    {commandName: "/requestcarry [player]", staff: false},
    {commandName: "/requestfire [description]", staff: false},
    {commandName: "/requestgag [PlayerID/PartOfName]", staff: false},
    {commandName: "/resetallboombox", staff: false},
    {commandName: "/resetboombox [targ]", staff: false},
    {commandName: "/resetphonecode [confirm]", staff: false},
    {commandName: "/respawnfarming", staff: false},
    {commandName: "/responding", staff: false},
    {commandName: "/restack", staff: false},
    {commandName: "/revive [target]", staff: false},
    {commandName: "/reward [targ] [amount]", staff: false},
    {commandName: "/roadblock", staff: false},
    {commandName: "/roadblockdel", staff: false},
    {commandName: "/rob [targ]", staff: false},
    {commandName: "/roe", staff: false},
    {commandName: "/roll [lowest] [highest]", staff: false},
    {commandName: "/rps", staff: false},
    {commandName: "/rules", staff: false},
    {commandName: "/s [message]", staff: false},
    {commandName: "/safe", staff: false},
    {commandName: "/safedeposit", staff: false},
    {commandName: "/safeitems", staff: false},
    {commandName: "/safewithdraw [amount]", staff: false},
    {commandName: "/safewithdrawall", staff: false},
    {commandName: "/sampleblood", staff: false},
    {commandName: "/savecam", staff: false},
    {commandName: "/saveset [name] [range]", staff: false},
    {commandName: "/scuba", staff: false},
    {commandName: "/searchdrugs", staff: false},
    {commandName: "/searchf [name]", staff: false},
    {commandName: "/searchguns", staff: false},
    {commandName: "/seatbelt", staff: false},
    {commandName: "/seize [action]", staff: false},
    {commandName: "/seizeitem [targ] [itemid] [amount]", staff: false},
    {commandName: "/seizeweapons [target]", staff: false},
    {commandName: "/sellalcohol", staff: false},
    {commandName: "/sellallfurniture", staff: false},
    {commandName: "/sellbusiness [confirm]", staff: false},
    {commandName: "/sellcarcass", staff: false},
    {commandName: "/sellcrate", staff: false},
    {commandName: "/sellfish", staff: false},
    {commandName: "/sellgrain", staff: false},
    {commandName: "/sellhouse [confirm]", staff: false},
    {commandName: "/sellvehicle [price] [player]", staff: false},
    {commandName: "/sendlocation [number or contact name]", staff: false},
    {commandName: "/sendnotification [targ] [message]", staff: false},
    {commandName: "/sendtohospital [target] - Requests that the player is NPC'd to the hospital.", staff: false},
    {commandName: "/sendtomorgue", staff: false},
    {commandName: "/setbetstep [1-1000]", staff: false},
    {commandName: "/setblinds [blinds 0-100000]", staff: false},
    {commandName: "/setbracelet [targ] [bracelet]", staff: false},
    {commandName: "/setbuildperm [targ]", staff: false},
    {commandName: "/setbusdest [text]", staff: false},
    {commandName: "/setclothes [slot] [drawable] [texture]", staff: false},
    {commandName: "/setcontainerdescription [storage id (if needed)]", staff: false},
    {commandName: "/setdep [Faction Short Name (i.e. LSPD, LSFD, etc) or Faction Group (i.e. LAW)]", staff: false},
    {commandName: "/setdevice [id]", staff: false},
    {commandName: "/setfrequency [slot] [frequency or frequency name]", staff: false},
    {commandName: "/setinjuries [injury description - brief, or 'clear' to clear it]", staff: false},
    {commandName: "/setjailstatus [targ] [status]", staff: false},
    {commandName: "/setjob [jobId] [targ]", staff: false},
    {commandName: "/setlawyer [targ]", staff: false},
    {commandName: "/setmainphone [phone number or name]", staff: false},
    {commandName: "/setopenbusiness", staff: false},
    {commandName: "/setorigin [origin]", staff: false},
    {commandName: "/setrentable [price]", staff: false},
    {commandName: "/setslot [slot or frequency name]", staff: false},
    {commandName: "/setstation [station]", staff: false},
    {commandName: "/setstep [step]", staff: false},
    {commandName: "/settings", staff: false},
    {commandName: "/settrashlocation", staff: false},
    {commandName: "/setup2fa", staff: false},
    {commandName: "/setvolume [volume]", staff: false},
    {commandName: "/setwaypoint [x] [y]", staff: false},
    {commandName: "/setwristband [targ] [wristband]", staff: false},
    {commandName: "/sheriffshat", staff: false},
    {commandName: "/shirt [on/off]", staff: false},
    {commandName: "/shoes [on/off]", staff: false},
    {commandName: "/shop [commandText]", staff: false},
    {commandName: "/shoutto [targ] [message]", staff: false},
    {commandName: "/showdriverlicense [targ]", staff: false},
    {commandName: "/showitem [targ] [itemid] [amount]", staff: false},
    {commandName: "/showitems [targ]", staff: false},
    {commandName: "/showlicenses [targ]", staff: false},
    {commandName: "/shownote [target] [itemid]", staff: false},
    {commandName: "/showrecord [target] [itemid]", staff: false},
    {commandName: "/showsafekeys", staff: false},
    {commandName: "/showtenants", staff: false},
    {commandName: "/showweapon [weapon]", staff: false},
    {commandName: "/showweaponlicense [targ]", staff: false},
    {commandName: "/showwristband [targ]", staff: false},
    {commandName: "/siren", staff: false},
    {commandName: "/sirenkey [up/down/horn] [button ('default' to reset)]", staff: false},
    {commandName: "/skiplicense", staff: false},
    {commandName: "/skiptransact", staff: false},
    {commandName: "/skipturn [player]", staff: false},
    {commandName: "/slots", staff: false},
    {commandName: "/sms [numberORname] [text]", staff: false},
    {commandName: "/smsback [message]", staff: false},
    {commandName: "/snakecam", staff: false},
    {commandName: "/sniffcar [action]", staff: false},
    {commandName: "/sniffdrugs [target]", staff: false},
    {commandName: "/sniffgun [target]", staff: false},
    {commandName: "/socks [on/off]", staff: false},
    {commandName: "/spectable", staff: false},
    {commandName: "/speedlimiter [speed/off]", staff: false},
    {commandName: "/spike", staff: false},
    {commandName: "/spitem [itemid] [amount]", staff: false},
    {commandName: "/startairsoft [weaponName] [actions (1 = enabled, 0 = disabled)]", staff: false},
    {commandName: "/startbus", staff: false},
    {commandName: "/startfarm", staff: false},
    {commandName: "/startgame", staff: false},
    {commandName: "/startmapping", staff: false},
    {commandName: "/startshift", staff: false},
    {commandName: "/startshipment", staff: false},
    {commandName: "/stashinfo [description]", staff: false},
    {commandName: "/stashitem [itemid] [amount] [description]", staff: false},
    {commandName: "/stats", staff: false},
    {commandName: "/stitem [itemid] [amount]", staff: false},
    {commandName: "/stolenvehiclelist", staff: false},
    {commandName: "/stopairsoft", staff: false},
    {commandName: "/stopalarm", staff: false},
    {commandName: "/stopallrent", staff: false},
    {commandName: "/stopbleeding [PlayerID/PartOfName]", staff: false},
    {commandName: "/stopcarry", staff: false},
    {commandName: "/stopcourier", staff: false},
    {commandName: "/stopdrag [targ]", staff: false},
    {commandName: "/stopeffect", staff: false},
    {commandName: "/stopface", staff: false},
    {commandName: "/stopfarm", staff: false},
    {commandName: "/stopfishing", staff: false},
    {commandName: "/stophose", staff: false},
    {commandName: "/stophotwire", staff: false},
    {commandName: "/stopmybleeding", staff: false},
    {commandName: "/stopnews", staff: false},
    {commandName: "/stoprent", staff: false},
    {commandName: "/stoptaxirent", staff: false},
    {commandName: "/styles [styleCategory] [styleName]", staff: false},
    {commandName: "/submitpin [pin]", staff: false},
    {commandName: "/suicide [confirm]", staff: false},
    {commandName: "/supplyphone [target] [amount]", staff: false},
    {commandName: "/surgery", staff: false},
    {commandName: "/switchfurnituremovement", staff: false},
    {commandName: "/switchseats", staff: false},
    {commandName: "/t [message]", staff: false},
    {commandName: "/take [Help/SlotID]", staff: false},
    {commandName: "/takeboombox", staff: false},
    {commandName: "/takecorpsefromtrunk", staff: false},
    {commandName: "/takedriverlicense [targ]", staff: false},
    {commandName: "/takefine [id]", staff: false},
    {commandName: "/takeitem", staff: false},
    {
        commandName: "/takelicense [target] [licenseid] (1=Driving license, 2=PF, 3=CCW, 4=LEOCCW, 5=Copper, 6=Iron, 7=Aluminium, 8=Guardcard, 12=Pilot, 18=CFIA, 19=CFIH, 20=PilotA, 21=PilotH)",
        staff: false
    },
    {commandName: "/takeplant", staff: false},
    {commandName: "/takespike [size]", staff: false},
    {commandName: "/taxi", staff: false},
    {commandName: "/taxiaccept [number]", staff: false},
    {commandName: "/taxidone", staff: false},
    {commandName: "/taxidriver [confirm]", staff: false},
    {commandName: "/taxirequests", staff: false},
    {commandName: "/taxistart", staff: false},
    {commandName: "/taxistop", staff: false},
    {commandName: "/testers", staff: false},
    {commandName: "/textsize [size]", staff: false},
    {commandName: "/time", staff: false},
    {commandName: "/timestamps", staff: false},
    {commandName: "/tlow [message]", staff: false},
    {commandName: "/to [targ] [message]", staff: false},
    {commandName: "/togad", staff: false},
    {commandName: "/togchatdraft", staff: false},
    {commandName: "/togchatvisuallyimpared [opacity]", staff: false},
    {commandName: "/toggleactiongradients", staff: false},
    {commandName: "/toggleambiencesound", staff: false},
    {commandName: "/toggleatc", staff: false},
    {commandName: "/toggleclicktomove", staff: false},
    {commandName: "/toggleconnectionqueue", staff: false},
    {commandName: "/toggledepartmental", staff: false},
    {commandName: "/togglefaction", staff: false},
    {commandName: "/toggleholsteranim [Mode] (Modes: 0 = Auto-Decide, Holster, Waistband)", staff: false},
    {commandName: "/toggleindicator", staff: false},
    {commandName: "/togglelstannouncement", staff: false},
    {commandName: "/toggleradio", staff: false},
    {commandName: "/toggleweaponwheel", staff: false},
    {commandName: "/togidlecamera", staff: false},
    {commandName: "/togphone", staff: false},
    {commandName: "/togtaxi", staff: false},
    {commandName: "/torpedo", staff: false},
    {commandName: "/totalobjects", staff: false},
    {commandName: "/trace [phone number]", staff: false},
    {commandName: "/traceparcel [code]", staff: false},
    {commandName: "/track", staff: false},
    {commandName: "/transact [Hash]", staff: false},
    {commandName: "/transfer [Amount] [Routing or player ID] [Comment (optional)]", staff: false},
    {commandName: "/trashitem [itemid] [amount]", staff: false},
    {commandName: "/treatmentitems [Methadone/Adderall/Oxycodone/Codeine/Valium/Bandage] [Amount]", staff: false},
    {commandName: "/triallist", staff: false},
    {commandName: "/triggeralarm", staff: false},
    {commandName: "/triggeredalarms", staff: false},
    {commandName: "/trunk [vehOverride]", staff: false},
    {commandName: "/trunkaccept", staff: false},
    {commandName: "/trunkdeny", staff: false},
    {commandName: "/trunkkidnap [targ]", staff: false},
    {commandName: "/trunkremove [targ]", staff: false},
    {commandName: "/unbugphone [number]", staff: false},
    {commandName: "/uncuff [targ]", staff: false},
    {commandName: "/undershirt [on/off]", staff: false},
    {commandName: "/undestroy [id]", staff: false},
    {commandName: "/unequip [weapon id]", staff: false},
    {commandName: "/unfreezeobj", staff: false},
    {commandName: "/uniform [quick]", staff: false},
    {commandName: "/uniformname [slot] [name (use 'clear' to clear the name)]", staff: false},
    {commandName: "/unimpound [vehicleId]", staff: false},
    {commandName: "/uninstallcharger [confirm]", staff: false},
    {commandName: "/unittype", staff: false},
    {commandName: "/unloadcrate", staff: false},
    {commandName: "/unloadgoods", staff: false},
    {commandName: "/unlockphone", staff: false},
    {commandName: "/unlockweapon [index]", staff: false},
    {commandName: "/unmute [target]", staff: false},
    {commandName: "/unmuteradio [slot]", staff: false},
    {commandName: "/unreadnotifications", staff: false},
    {commandName: "/uptime", staff: false},
    {commandName: "/useitem [itemid]", staff: false},
    {commandName: "/vacation [confirm]", staff: false},
    {commandName: "/vbreakin [vehOverride]", staff: false},
    {commandName: "/vdoor [door]", staff: false},
    {commandName: "/vehattach", staff: false},
    {commandName: "/vehicleantitheft", staff: false},
    {commandName: "/vehicledetails", staff: false},
    {commandName: "/vehiclefines", staff: false},
    {commandName: "/vehicleget [id]", staff: false},
    {commandName: "/vehiclepark", staff: false},
    {commandName: "/vehitems [vehOverride]", staff: false},
    {commandName: "/vehmenu", staff: false},
    {commandName: "/vehoff", staff: false},
    {commandName: "/vehplaceitem [itemid] [amount]", staff: false},
    {commandName: "/vehplaceitems", staff: false},
    {commandName: "/vehtakeitem [itemid] [amount]", staff: false},
    {commandName: "/vehtakeitems", staff: false},
    {commandName: "/vest [index]", staff: false},
    {commandName: "/vexamine [target]", staff: false},
    {commandName: "/vfine [amount] [reason]", staff: false},
    {commandName: "/viewat", staff: false},
    {commandName: "/viewboombox", staff: false},
    {commandName: "/vnearby [distance]", staff: false},
    {commandName: "/vneon", staff: false},
    {commandName: "/voicemail [message]", staff: false},
    {commandName: "/vote [candidateID]", staff: false},
    {commandName: "/vplate", staff: false},
    {commandName: "/vrestream", staff: false},
    {commandName: "/vscrap [confirm]", staff: false},
    {commandName: "/vstats [playerid?]", staff: false},
    {commandName: "/vunbusiness", staff: false},
    {commandName: "/vunfaction", staff: false},
    {commandName: "/vwindow [window]", staff: false},
    {commandName: "/w [targ] [message]", staff: false},
    {commandName: "/wa", staff: false},
    {commandName: "/walk", staff: false},
    {commandName: "/warehouse", staff: false},
    {commandName: "/watch [on/off]", staff: false},
    {commandName: "/weaponclean [itemid]", staff: false},
    {commandName: "/weaponrepair [itemid]", staff: false},
    {commandName: "/weapons", staff: false},
    {commandName: "/weather", staff: false},
    {commandName: "/weedstatus", staff: false},
    {commandName: "/wheelmode", staff: false},
    {commandName: "/whistle", staff: false},
    {commandName: "/wireaccept", staff: false},
    {commandName: "/wireremove", staff: false},
    {commandName: "/withdraw [target]", staff: false},
    {commandName: "/wre [message]", staff: false},
    {commandName: "/youtube [videoid]", staff: false},
    {commandName: "/a [Message]", staff: true},
    {commandName: "/ac4screen [target]", staff: true},
    {commandName: "/acceptreport [reportId]", staff: true},
    {commandName: "/acceptrequest [requestId]", staff: true},
    {commandName: "/acheckanklemonitor [Player ID/Part Of Name]", staff: true},
    {commandName: "/acleancar", staff: true},
    {commandName: "/aclearorders", staff: true},
    {commandName: "/acreateinformationmarker [days] [description] [image url: optional]", staff: true},
    {commandName: "/acreateitem [type] [value] [amount] [name]", staff: true},
    {commandName: "/addadminhistory [targ] [message]", staff: true},
    {commandName: "/addcasinogame [type] [businessId]", staff: true},
    {commandName: "/addfactionflag [organization] [flag]", staff: true},
    {commandName: "/addfactionvehicle [organization] [primaryColor] [secondaryColor]", staff: true},
    {commandName: "/addfurniture [model] [price] [category] [name]", staff: true},
    {commandName: "/addfurniturecategory [name]", staff: true},
    {commandName: "/addperm [targ] [text]", staff: true},
    {commandName: "/addprop", staff: true},
    {commandName: "/addsupplier [FirstName] [LastName] [type]", staff: true},
    {commandName: "/addxmr", staff: true},
    {commandName: "/adeleteanklemonitor [Player ID/Part Of Name]", staff: true},
    {commandName: "/adeleteinformationmarker", staff: true},
    {commandName: "/adeletescene", staff: true},
    {commandName: "/adetach [weaponIndex] [componentIndex]", staff: true},
    {commandName: "/admin2objectmenu", staff: true},
    {commandName: "/admincar [model]", staff: true},
    {commandName: "/adminengine", staff: true},
    {commandName: "/adminflip", staff: true},
    {commandName: "/adminftow [organization]", staff: true},
    {commandName: "/adminjail [targ] [minutes] [reason]", staff: true},
    {commandName: "/adminlock", staff: true},
    {commandName: "/adminobjectmenu", staff: true},
    {commandName: "/admintow", staff: true},
    {commandName: "/adminvehoff", staff: true},
    {commandName: "/adruginfo [PlayerID/PartOfName]", staff: true},
    {commandName: "/aduty", staff: true},
    {commandName: "/afactiononline [factionId]", staff: true},
    {commandName: "/afire [fire ID]", staff: true},
    {commandName: "/agag [PlayerID/PartOfName]", staff: true},
    {commandName: "/agiveanklemonitor [Player ID/Part Of Name]", staff: true},
    {
        commandName: "/agiveboombox [Player ID/Part Of Name] [small/medium/large] - Add boombox to inventory.",
        staff: true
    },
    {commandName: "/ahelp", staff: true},
    {commandName: "/ainstalllock", staff: true},
    {commandName: "/allowrobbery [targ]", staff: true},
    {commandName: "/alockweapon [targ] [index]", staff: true},
    {commandName: "/animaldata", staff: true},
    {commandName: "/answerticket [ticketId] [answer]", staff: true},
    {commandName: "/aorders", staff: true},
    {commandName: "/approverequest [requestId] [confirm]", staff: true},
    {commandName: "/approvetransfer [targ]", staff: true},
    {commandName: "/apropertyinfo", staff: true},
    {commandName: "/apropertylock", staff: true},
    {commandName: "/aremovegag [PlayerID/PartOfName]", staff: true},
    {commandName: "/aremoveserial [targ] [index]", staff: true},
    {commandName: "/arevive [target]", staff: true},
    {commandName: "/asearchf [name]", staff: true},
    {commandName: "/asetdirt [dirt]", staff: true},
    {commandName: "/asetmarker [targ] [x] [y]", staff: true},
    {commandName: "/aslots", staff: true},
    {commandName: "/astopbleeding [PlayerID/PartOfName]", staff: true},
    {commandName: "/atrace [targ]", staff: true},
    {commandName: "/attachobjectdev [item] [bone] [x] [y] [z] [rx] [ry] [rz]", staff: true},
    {commandName: "/authorizecef [value]", staff: true},
    {commandName: "/avmod", staff: true},
    {commandName: "/avmodex", staff: true},
    {commandName: "/aweaponclean [itemid] [value]", staff: true},
    {commandName: "/aweaponrepair [itemid] [value]", staff: true},
    {commandName: "/ban [targ] [days] [mins] [reason]", staff: true},
    {commandName: "/banjob [targ]", staff: true},
    {commandName: "/bankdoors [locked] [heading]", staff: true},
    {commandName: "/bbank [price]", staff: true},
    {commandName: "/bblip [blipId] [blipColor]", staff: true},
    {commandName: "/bcomp [comp]", staff: true},
    {commandName: "/bcompprice [comp]", staff: true},
    {commandName: "/bcreate [ownable] [price] [type] [iconId] [iconColor] [name]", staff: true},
    {commandName: "/bdelete", staff: true},
    {commandName: "/bfaction [faction]", staff: true},
    {commandName: "/bgarage [businessId] [confirm]", staff: true},
    {commandName: "/binfo", staff: true},
    {commandName: "/bmaxcomp [comp]", staff: true},
    {commandName: "/bmove [id]", staff: true},
    {commandName: "/bname [name]", staff: true},
    {commandName: "/bnearby [distance]", staff: true},
    {commandName: "/bonushp [amount]", staff: true},
    {commandName: "/boomboxinfo [Distance (default 25)] - Get detailed stats of nearest boombox.", staff: true},
    {commandName: "/boomboxrange [Distance (default 5)] - Set nearest boombox range.", staff: true},
    {commandName: "/bownable", staff: true},
    {commandName: "/bowner [targ]", staff: true},
    {commandName: "/bowneroffline [characterID]", staff: true},
    {commandName: "/bprice [price]", staff: true},
    {commandName: "/broleplay", staff: true},
    {commandName: "/bteleport [businessID]", staff: true},
    {commandName: "/btype [type]", staff: true},
    {commandName: "/casinogamesnearme", staff: true},
    {commandName: "/casinogameteleport [id]", staff: true},
    {commandName: "/cdelete", staff: true},
    {commandName: "/changetoreport [ticketId]", staff: true},
    {commandName: "/changetoticket [reportId]", staff: true},
    {commandName: "/check [targ]", staff: true},
    {commandName: "/checkhandle", staff: true},
    {commandName: "/checkjobpayments", staff: true},
    {commandName: "/checkpf [targ] [index]", staff: true},
    {commandName: "/ck [targ]", staff: true},
    {commandName: "/cleanpartnership [playerid]", staff: true},
    {commandName: "/cleanshift", staff: true},
    {commandName: "/clearemployees", staff: true},
    {commandName: "/clearfrequencyname [channel]", staff: true},
    {commandName: "/clearreports [confirm]", staff: true},
    {commandName: "/clearrequests [confirm]", staff: true},
    {commandName: "/createbloodlab [Faction ID (See /listfactions)]", staff: true},
    {commandName: "/createcell [name]", staff: true},
    {commandName: "/createcharger", staff: true},
    {commandName: "/createcorp [targ] [deathReason]", staff: true},
    {commandName: "/createdealership [sprite ID] [name]", staff: true},
    {commandName: "/createelevator", staff: true},
    {commandName: "/createlocker [factionID] [maxentries]", staff: true},
    {
        commandName: "/createmultiinterior [exteriorDimension] [interior] [ownable] [roomPrice] [floorCount] [roomCount] [invSize] [name]",
        staff: true
    },
    {commandName: "/createpayphone [model or type]", staff: true},
    {commandName: "/createproperty [type] [exteriorDimension] [interior] [ownable] [price] [size] [name]", staff: true},
    {commandName: "/createsmarttp [propertyID] [markerBool] [canUsePropCmd] [type] [tpName]", staff: true},
    {commandName: "/createsupplier [name]", staff: true},
    {commandName: "/createvehicle [targ] [model]", staff: true},
    {commandName: "/dcrun [code]", staff: true},
    {commandName: "/debugdata", staff: true},
    {commandName: "/debuggroupchats", staff: true},
    {commandName: "/debugvehdata", staff: true},
    {commandName: "/deldminhistory [targ]", staff: true},
    {commandName: "/delentities [range]", staff: true},
    {commandName: "/deleteallblood [Range(Recommended is 30)]", staff: true},
    {commandName: "/deleteblood", staff: true},
    {commandName: "/deletebloodlab", staff: true},
    {commandName: "/deleteboombox [Distance (default 25)] - Delete nearest boombox.", staff: true},
    {commandName: "/deletecasinogame [id]", staff: true},
    {commandName: "/deletecell", staff: true},
    {commandName: "/deleteplayeritem [targ] [itemid] [amount]", staff: true},
    {commandName: "/deleteserverblood [Range(Recommended is 30)]", staff: true},
    {commandName: "/deletesmarttp [propertyID] [teleportID]", staff: true},
    {commandName: "/deletesupplier [confirm]", staff: true},
    {commandName: "/deletevehiclebusinessgarage [factionID] [garageID]", staff: true},
    {commandName: "/deletevehiclegarage [factionID] [garageID]", staff: true},
    {commandName: "/deleteweed", staff: true},
    {commandName: "/deleteworldobject [Hash] [X] [Y] [Z] [Save 1 = yes, 0 = no]", staff: true},
    {commandName: "/deleventvehicle", staff: true},
    {commandName: "/delfurniture [name]", staff: true},
    {commandName: "/dellaptop", staff: true},
    {commandName: "/delobject [range]", staff: true},
    {commandName: "/delprop", staff: true},
    {commandName: "/devclearguns", staff: true},
    {commandName: "/devcoords", staff: true},
    {commandName: "/devgivegun [id]", staff: true},
    {commandName: "/devicecreate [name]", staff: true},
    {commandName: "/devicedelete", staff: true},
    {commandName: "/devicetp [deviceId]", staff: true},
    {commandName: "/disablefuel", staff: true},
    {commandName: "/disablevalarm", staff: true},
    {commandName: "/dsgoto [ID]", staff: true},
    {commandName: "/dsinfo [id]", staff: true},
    {commandName: "/dsvadd [price] [model] [category] [friendly name]", staff: true},
    {commandName: "/dsvedit [Model] [Price] [Friendly Name]", staff: true},
    {commandName: "/dsvlist", staff: true},
    {commandName: "/dsvremove [model]", staff: true},
    {commandName: "/editcasinogame [id] [businessId]", staff: true},
    {commandName: "/editfrequencyname [channel] [name]", staff: true},
    {commandName: "/editpayphone [label]", staff: true},
    {commandName: "/enable [chat]", staff: true},
    {commandName: "/enablewp [streak]", staff: true},
    {commandName: "/entdata [target]", staff: true},
    {commandName: "/enterclosestcar", staff: true},
    {commandName: "/enterclosestseat [seatID]", staff: true},
    {commandName: "/eventvehicle [model] [primaryColor] [secondaryColor]", staff: true},
    {commandName: "/explosion [explosion]", staff: true},
    {commandName: "/factionvehicles [targ]", staff: true},
    {commandName: "/fbiz [org] [0=disable 1=enable]", staff: true},
    {commandName: "/fcreate [targ] [shortname] [name]", staff: true},
    {commandName: "/fdelete [organizationId]", staff: true},
    {commandName: "/fgarage [garageID] [confirm]", staff: true},
    {commandName: "/finalizecharger", staff: true},
    {commandName: "/finalizepayphone [area code] [prison 1 = yes]", staff: true},
    {commandName: "/findname [range]", staff: true},
    {commandName: "/finfo [targ]", staff: true},
    {commandName: "/firerequests", staff: true},
    {commandName: "/fixmyspec", staff: true},
    {commandName: "/fixvehicle", staff: true},
    {commandName: "/football_player_with_lowest_ping", staff: true},
    {commandName: "/forceacceptdeath [target] [minutes]", staff: true},
    {commandName: "/forceallspecoff", staff: true},
    {commandName: "/forcebreakup [playerid]", staff: true},
    {commandName: "/forcepaycheck [targ] [times]", staff: true},
    {commandName: "/forcerelease [targ]", staff: true},
    {commandName: "/forceresults [serial]", staff: true},
    {commandName: "/forcespecoff [targ]", staff: true},
    {commandName: "/forcestopcarry [target]", staff: true},
    {commandName: "/forcesuicide [pistol/poison] target", staff: true},
    {commandName: "/forceupgrade", staff: true},
    {commandName: "/freeze [targ]", staff: true},
    {commandName: "/frename [org] [name]", staff: true},
    {commandName: "/fshortname [org] [name]", staff: true},
    {commandName: "/fspectate [id]", staff: true},
    {commandName: "/fspectateall", staff: true},
    {commandName: "/fspectatestop", staff: true},
    {commandName: "/garbageforcerespawn", staff: true},
    {commandName: "/getadminhistory [targ]", staff: true},
    {commandName: "/getanimaldebug", staff: true},
    {commandName: "/getanimalinfo", staff: true},
    {commandName: "/getback [targ]", staff: true},
    {commandName: "/getbloodname [DNA String]", staff: true},
    {commandName: "/getbloodstring [PlayerID/PartOfName]", staff: true},
    {commandName: "/getdeaths [targ]", staff: true},
    {commandName: "/getdimension [targ]", staff: true},
    {commandName: "/gethash [toHash]", staff: true},
    {commandName: "/gethere [targ]", staff: true},
    {commandName: "/getitemid", staff: true},
    {commandName: "/getmaskname [maskName]", staff: true},
    {commandName: "/getplayersafe [Player ID]", staff: true},
    {commandName: "/getvehiclegarage", staff: true},
    {commandName: "/getvehicleid", staff: true},
    {commandName: "/getweapons [targ]", staff: true},
    {commandName: "/giveammo [targ] [weapon] [count]", staff: true},
    {commandName: "/givebank [target] [amount]", staff: true},
    {commandName: "/givecash [target] [amount]", staff: true},
    {commandName: "/giveplayeritem [targ] [amount] [itemname]", staff: true},
    {commandName: "/giveplayeritemid [targ] [amount] [itemname]", staff: true},
    {commandName: "/amoveallfurniture [posX] [posY] [posZ]", staff: true},
    {commandName: "/givepropertyitem [propertyId] [amount] [itemname]", staff: true},
    {commandName: "/givepropertyitemid [propertyId] [amount] [itemname]", staff: true},
    {commandName: "/giveweapon [targ] [weapon]", staff: true},
    {commandName: "/giveweaponcomponent [targ] [amount] [weaponType] [component]", staff: true},
    {commandName: "/goback", staff: true},
    {commandName: "/goto [location]", staff: true},
    {commandName: "/goto2", staff: true},
    {commandName: "/gotobloodlab [labID]", staff: true},
    {commandName: "/gotobusiness [businessName]", staff: true},
    {commandName: "/gotocoord [x] [y] [z]", staff: true},
    {commandName: "/gotointerior [interiorNameOrID]", staff: true},
    {commandName: "/gotomultiinterior [multiinteriorName]", staff: true},
    {commandName: "/gotopayphone [number]", staff: true},
    {commandName: "/gotoprop [address]", staff: true},
    {commandName: "/gotosafe [Safe ID]", staff: true},
    {commandName: "/gotowaypoint", staff: true},
    {commandName: "/gotoweed [weedID]", staff: true},
    {commandName: "/inactivitycheck [days]", staff: true},
    {commandName: "/increasestreak [streak]", staff: true},
    {commandName: "/intarr [test1] [test2] [test3]", staff: true},
    {commandName: "/invisibility", staff: true},
    {commandName: "/kick [player] [note on record 1=yes/0=no] [reason]", staff: true},
    {commandName: "/lastincar", staff: true},
    {commandName: "/linksmarttp [propertyID] [teleportID] [teleportIDToLinkTo]", staff: true},
    {commandName: "/listcasinogames", staff: true},
    {commandName: "/listcasinogamesbybusiness [businessId]", staff: true},
    {commandName: "/listcategory [name]", staff: true},
    {commandName: "/listfactions", staff: true},
    {commandName: "/listitemtemplates", staff: true},
    {commandName: "/listshift", staff: true},
    {commandName: "/listspectators", staff: true},
    {commandName: "/listveh [vehName]", staff: true},
    {commandName: "/livery [livery]", staff: true},
    {commandName: "/loadmap [propertyId] [mapfile] [confirm]", staff: true},
    {commandName: "/loadobjects [name]", staff: true},
    {commandName: "/loadpoi", staff: true},
    {commandName: "/manageradios", staff: true},
    {commandName: "/markerinfo", staff: true},
    {commandName: "/massadmincar [model] [amount]", staff: true},
    {commandName: "/massadmintow [range]", staff: true},
    {commandName: "/menufurniture", staff: true},
    {commandName: "/mgt [Message]", staff: true},
    {commandName: "/move [targ] [direction] [value]", staff: true},
    {commandName: "/movecasinogame [id]", staff: true},
    {commandName: "/movecell [cellId]", staff: true},
    {commandName: "/movesmarttp [propertyID] [teleportID]", staff: true},
    {commandName: "/movesupplier [supplier ID] [Main Position = 0, Interaction Position = 1]", staff: true},
    {
        commandName: "/multiinterioraddfloor [multiinteriorID] [interior] [ownable] [roomPrice] [roomCount] [invSize] [name]",
        staff: true
    },
    {commandName: "/multiinterioraddrooms", staff: true},
    {commandName: "/multiinteriorallinterior [multiinteriorID] [interior]", staff: true},
    {commandName: "/multiinteriorallnpcrent [multiinteriorID] [rentPrice]", staff: true},
    {commandName: "/multiinteriorallownable [multiinteriorID] [ownable]", staff: true},
    {commandName: "/multiinteriorallowner [multiinteriorID] [targ]", staff: true},
    {commandName: "/multiinteriorallowneroffline [multiinteriorID] [owner]", staff: true},
    {commandName: "/multiinteriorallprice [multiinteriorID] [price]", staff: true},
    {commandName: "/multiinteriordelete [multiinteriorID]", staff: true},
    {commandName: "/multiinteriorinfo", staff: true},
    {commandName: "/multiinteriormove [multiinteriorID]", staff: true},
    {commandName: "/multiinteriornearby [distance]", staff: true},
    {commandName: "/multiinteriorrename [multiinteriorID] [name]", staff: true},
    {commandName: "/multiinteriorteleport [multiinteriorID]", staff: true},
    {commandName: "/myloginmessages", staff: true},
    {commandName: "/nametag", staff: true},
    {commandName: "/newplayer [new_name]", staff: true},
    {commandName: "/newplayerstop", staff: true},
    {commandName: "/noclipspeed [value]", staff: true},
    {commandName: "/outfithistory [player]", staff: true},
    {commandName: "/pcondition [0 = False, 1 = True]", staff: true},
    {commandName: "/pdelete [propertyId] [confirm]", staff: true},
    {commandName: "/permban [targ] [reason]", staff: true},
    {commandName: "/pinterior [propertyId] [interior] [confirm]", staff: true},
    {commandName: "/pinvclear [propertyID] [confirm]", staff: true},
    {commandName: "/playerproperties [targ]", staff: true},
    {commandName: "/playerpropertiesoffline [characterID]", staff: true},
    {commandName: "/playerslist", staff: true},
    {commandName: "/playervehicles [targ]", staff: true},
    {commandName: "/playervehiclesoffline [characterid]", staff: true},
    {commandName: "/playerweedstats [target]", staff: true},
    {commandName: "/pmove [propertyId] [confirm]", staff: true},
    {commandName: "/pnearby [distance]", staff: true},
    {commandName: "/pnotes [editing]", staff: true},
    {commandName: "/pool_check_flood_events_count", staff: true},
    {commandName: "/pownable [propertyId] [ownable]", staff: true},
    {commandName: "/powner [propertyId] [resetPurchaseDate] [targ]", staff: true},
    {commandName: "/powneroffline [propertyID] [resetPurchaseDate] [characterID]", staff: true},
    {commandName: "/pprice [propertyId] [price]", staff: true},
    {commandName: "/prename [propertyId] [name]", staff: true},
    {commandName: "/previewmap [dimensionId] [mapfile]", staff: true},
    {commandName: "/previewmaplist", staff: true},
    {commandName: "/propertyactivity", staff: true},
    {commandName: "/propertyadmin", staff: true},
    {commandName: "/psetfaction [propertyId] [faction] [confirm]", staff: true},
    {commandName: "/pteleport [propertyId]", staff: true},
    {commandName: "/ptype [propertyId] [type]", staff: true},
    {commandName: "/refreshanim", staff: true},
    {commandName: "/rehash [full]", staff: true},
    {commandName: "/rehashcasings [full]", staff: true},
    {commandName: "/rehashveh [full]", staff: true},
    {commandName: "/removeallbrewery [confirm]", staff: true},
    {commandName: "/removealleventvehicles", staff: true},
    {commandName: "/removeatrace", staff: true},
    {commandName: "/removebrewery", staff: true},
    {commandName: "/removefactionflag [organization] [flag]", staff: true},
    {commandName: "/removefactionvehicle", staff: true},
    {commandName: "/removefromtest [targ]", staff: true},
    {commandName: "/removesupplier [FirstName] [LastName]", staff: true},
    {commandName: "/removetext", staff: true},
    {commandName: "/reports", staff: true},
    {commandName: "/requests", staff: true},
    {commandName: "/resetafk [targ]", staff: true},
    {commandName: "/resetcasinogame [id]", staff: true},
    {commandName: "/resetdriving", staff: true},
    {commandName: "/resetveh", staff: true},
    {commandName: "/respawnanimals", staff: true},
    {commandName: "/restart", staff: true},
    {commandName: "/restartbot", staff: true},
    {commandName: "/sandboxmode", staff: true},
    {commandName: "/sceneinfo", staff: true},
    {commandName: "/seeafk [targ]", staff: true},
    {commandName: "/seefactionflags [organization]", staff: true},
    {commandName: "/seefactionwages [organization]", staff: true},
    {commandName: "/seeitems [targ]", staff: true},
    {commandName: "/sendto [target] [location]", staff: true},
    {commandName: "/sendtobusiness [targ] [businessName]", staff: true},
    {commandName: "/sendtoproperty [targ] [propertyName]", staff: true},
    {commandName: "/senior [Message]", staff: true},
    {commandName: "/seniorann [Message]", staff: true},
    {commandName: "/setage [target] [age]", staff: true},
    {commandName: "/setarmour [targ] [value]", staff: true},
    {commandName: "/setbankname [routing] [newname]", staff: true},
    {commandName: "/setbloodtype [PlayerID/PartOfName] [A+/A-/B+/B-/O+/O-/AB+/AB-]", staff: true},
    {commandName: "/setdimension [targ] [dimension]", staff: true},
    {commandName: "/setdrunklevel [targ] [level]", staff: true},
    {commandName: "/setdrunkresistance [targ] [level]", staff: true},
    {commandName: "/setevidencelocker [lockerid] [argument] [extra]", staff: true},
    {commandName: "/setfaction [targ] [organization]", staff: true},
    {commandName: "/setfactionhotline [org] [newHotline]", staff: true},
    {commandName: "/setfactionrank [targ] [rank]", staff: true},
    {commandName: "/setfactionrankname [targ] [rank]", staff: true},
    {commandName: "/setfuel [fuel]", staff: true},
    {commandName: "/setgps", staff: true},
    {commandName: "/setharvestmultiplier [target] [harvestMultiplier]", staff: true},
    {commandName: "/sethealth [targ] [value] [ignoreSafety]", staff: true},
    {commandName: "/setinvisibility [targ]", staff: true},
    {commandName: "/setitemname [targ] [index] [amount] [name]", staff: true},
    {commandName: "/setitempurity [targ] [index] [amount] [purity]", staff: true},
    {commandName: "/setjobpayments [amount]", staff: true},
    {commandName: "/setloginmessage [firstname] [lastname] [message]", staff: true},
    {commandName: "/setmileage [amount]", staff: true},
    {commandName: "/setmod [mod_type] [mod_value]", staff: true},
    {commandName: "/setname [targ] [firstname] [lastname]", staff: true},
    {commandName: "/setprice [type] [price]", staff: true},
    {commandName: "/setpropertylimit [targ] [amount]", staff: true},
    {commandName: "/setpropertylimitoffline [characterId] [amount]", staff: true},
    {commandName: "/setprops [slot] [drawable] [texture]", staff: true},
    {commandName: "/setrecoil [modifier]", staff: true},
    {commandName: "/setscreeneffect [targ] [effectName] [loop] [time]", staff: true},
    {commandName: "/setskin [targ] [skin]", staff: true},
    {commandName: "/setsnow [snow]", staff: true},
    {commandName: "/settempname [targ] [name]", staff: true},
    {commandName: "/settenantlimit [amount]", staff: true},
    {commandName: "/settime [time]", staff: true},
    {commandName: "/setvalarm [alarmLevel]", staff: true},
    {commandName: "/setvehicle [argument] [extra]", staff: true},
    {commandName: "/setvehiclegarage [FactionID] [garageID]", staff: true},
    {commandName: "/setvlock [lockLevel]", staff: true},
    {commandName: "/setweather [weather]", staff: true},
    {commandName: "/setweedgrowthmultiplier [target] [growthMultiplier]", staff: true},
    {commandName: "/silentban [targ] [days] [mins] [reason]", staff: true},
    {commandName: "/skin [skin]", staff: true},
    {commandName: "/slap [targ]", staff: true},
    {commandName: "/slay [targ]", staff: true},
    {commandName: "/snow", staff: true},
    {commandName: "/snowlevel [description]", staff: true},
    {commandName: "/soccer_controller_info", staff: true},
    {
        commandName: "/spawnblood [PlayerID/PartOfName] [Time(default is ~r~10~w~, use ~r~0~w~ for no bleeding)]",
        staff: true
    },
    {commandName: "/spectate [targ]", staff: true},
    {commandName: "/spermban [targ] [reason]", staff: true},
    {commandName: "/spikeowner", staff: true},
    {commandName: "/staff [Message]", staff: true},
    {commandName: "/stopscreeneffect [targ] [effectName]", staff: true},
    {commandName: "/stopspectate", staff: true},
    {commandName: "/stpnearby [distance]", staff: true},
    {commandName: "/supplier [FirstName] [LastName]", staff: true},
    {commandName: "/supplierinfo", staff: true},
    {commandName: "/supplieritems [add/remove] [item]", staff: true},
    {commandName: "/suppliername [name]", staff: true},
    {commandName: "/suppliers [type]", staff: true},
    {commandName: "/supplierstock [stock]", staff: true},
    {commandName: "/supplycontainer [container name]", staff: true},
    {commandName: "/supplydrug [drugs name]", staff: true},
    {
        commandName: "/supplydrugscontainer [amount of containers] [amount of drugs per container] [purity] [container name]",
        staff: true
    },
    {commandName: "/syncfromdb", staff: true},
    {commandName: "/takebank [target] [amount]", staff: true},
    {commandName: "/takecash [target] [amount]", staff: true},
    {commandName: "/tduty", staff: true},
    {commandName: "/tempname [name]", staff: true},
    {commandName: "/test1 [effect]", staff: true},
    {commandName: "/test2 [effect]", staff: true},
    {commandName: "/test3 [effect1] [effect2]", staff: true},
    {commandName: "/testbuttoninput [target]", staff: true},
    {commandName: "/tfire [fire ID] [trash reason]", staff: true},
    {commandName: "/tickets", staff: true},
    {commandName: "/toggle [option]", staff: true},
    {commandName: "/totalafk", staff: true},
    {commandName: "/tp [targ]", staff: true},
    {commandName: "/tpgarbage", staff: true},
    {commandName: "/tplocs", staff: true},
    {commandName: "/tpplayertoplayer [targ] [toPlayer]", staff: true},
    {commandName: "/tpto [targ] [destination_targ]", staff: true},
    {commandName: "/tptodoor [id]", staff: true},
    {commandName: "/trashreport [reportId] [reason]", staff: true},
    {commandName: "/trashrequest [requestId] [trashReason]", staff: true},
    {commandName: "/trialcar [car_name]", staff: true},
    {commandName: "/unadminjail [targ]", staff: true},
    {commandName: "/unbanjob [targ]", staff: true},
    {commandName: "/unfreeze [targ]", staff: true},
    {commandName: "/unpreviewmap [mapfile]", staff: true},
    {commandName: "/vatcalculation [month] [year] [provider]", staff: true},
    {commandName: "/vbusiness [businessID]", staff: true},
    {commandName: "/vehcol [primaryColor] [secondaryColor]", staff: true},
    {commandName: "/vehentdata", staff: true},
    {commandName: "/vfaction", staff: true},
    {commandName: "/vgetoffline [vehId]", staff: true},
    {commandName: "/viewplayercontracts [target]", staff: true},
    {commandName: "/viewpropertycontainers", staff: true},
    {commandName: "/viewsmarttps [propertyID]", staff: true},
    {commandName: "/vinfo", staff: true},
    {commandName: "/vunregister", staff: true},
    {commandName: "/warn [targ] [reason]", staff: true},
    {commandName: "/weaponlist", staff: true},
    {commandName: "/weedinfo", staff: true},
    {commandName: "/whohasphone [number]", staff: true},
    {commandName: "/whoisbank [accountId]", staff: true},
];
