{
'use strict'; // code generated by pbf v3.2.1

// NetMessage ========================================

var NetMessage = self.NetMessage = {};

NetMessage.read = function (pbf, end) {
    return pbf.readFields(NetMessage._readField, {sequence_number: 0, messages: [], formats: [], messageRepeatCount: [], ints: [], floats: [], booleans: [], strings: [], vectors: []}, end);
};
NetMessage._readField = function (tag, obj, pbf) {
    if (tag === 1) obj.sequence_number = pbf.readVarint(true);
    else if (tag === 2) pbf.readPackedVarint(obj.messages, true);
    else if (tag === 3) obj.formats.push(pbf.readString());
    else if (tag === 4) pbf.readPackedVarint(obj.messageRepeatCount, true);
    else if (tag === 5) pbf.readPackedVarint(obj.ints, true);
    else if (tag === 6) pbf.readPackedFloat(obj.floats);
    else if (tag === 7) pbf.readPackedBoolean(obj.booleans);
    else if (tag === 8) obj.strings.push(pbf.readString());
    else if (tag === 9) obj.vectors.push(NetMessage.Vector3D.read(pbf, pbf.readVarint() + pbf.pos));
};
NetMessage.write = function (obj, pbf) {
    if (obj.sequence_number) pbf.writeVarintField(1, obj.sequence_number);
    if (obj.messages) pbf.writePackedVarint(2, obj.messages);
    if (obj.formats) for (var i = 0; i < obj.formats.length; i++) pbf.writeStringField(3, obj.formats[i]);
    if (obj.messageRepeatCount) pbf.writePackedVarint(4, obj.messageRepeatCount);
    if (obj.ints) pbf.writePackedVarint(5, obj.ints);
    if (obj.floats) pbf.writePackedFloat(6, obj.floats);
    if (obj.booleans) pbf.writePackedBoolean(7, obj.booleans);
    if (obj.strings) for (i = 0; i < obj.strings.length; i++) pbf.writeStringField(8, obj.strings[i]);
    if (obj.vectors) for (i = 0; i < obj.vectors.length; i++) pbf.writeMessage(9, NetMessage.Vector3D.write, obj.vectors[i]);
};

// NetMessage.Vector3D ========================================

NetMessage.Vector3D = {};

NetMessage.Vector3D.read = function (pbf, end) {
    return pbf.readFields(NetMessage.Vector3D._readField, {x: 0, y: 0, z: 0}, end);
};
NetMessage.Vector3D._readField = function (tag, obj, pbf) {
    if (tag === 1) obj.x = pbf.readFloat();
    else if (tag === 2) obj.y = pbf.readFloat();
    else if (tag === 3) obj.z = pbf.readFloat();
};
NetMessage.Vector3D.write = function (obj, pbf) {
    if (obj.x) pbf.writeFloatField(1, obj.x);
    if (obj.y) pbf.writeFloatField(2, obj.y);
    if (obj.z) pbf.writeFloatField(3, obj.z);
};

}